name: pitboard_flutter_app
description: Placeholder pubspec for Pitboard demo app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
